"""Emit the interactive lens figure's data block from the same _data.npz that
plot.py draws the static figures from.

    python3 make_lens_data.py        # rewrites _lens-data.html

The post's last section argues that DLA and activation patching disagree about
exactly one head. The interactive figure lets a reader flip the lens over a
fixed grid and watch that happen. Its numbers must therefore be THE numbers —
so they are generated here rather than typed, and re-running compute.py means
re-running this file too.

Scope is layers 8-11: patch_heads() in compute.py starts at layer 8, so those
are the only rows where both lenses exist. DLA ranks, however, are computed
over all 144 heads, because "138th of 144" is the claim the post makes.

The output is an HTML partial holding one JSON script tag, included by
index.qmd. Underscore-prefixed so Quarto never renders it as a page of its own.
"""

import json
from pathlib import Path

import numpy as np

HERE = Path(__file__).parent
LAYER_START = 8

# Exactly the five heads the post outlines and names — no more. The IOI paper
# names a wider family (9.6 and 10.0 are also name movers); this figure is not
# the place to introduce roles the surrounding prose never establishes.
ROLES = {
    (8, 6): "S-inhibition",
    (8, 10): "S-inhibition",
    (9, 9): "name mover",
    (10, 7): "negative name mover",
    (11, 10): "negative name mover",
}


def main() -> None:
    d = np.load(HERE / "_data.npz", allow_pickle=True)
    dla_flat = d["dla"].astype(float)  # [144], flat (layer * 12 + head)
    patch = d["heads"].astype(float)  # [12, 12], rows 0-7 are unmeasured zeros
    n_layers, n_heads = patch.shape

    # Rank 1 = the largest direct contribution, over the whole model.
    order = np.argsort(-dla_flat)
    rank = {int(idx): i + 1 for i, idx in enumerate(order)}

    cells = []
    for layer in range(LAYER_START, n_layers):
        for head in range(n_heads):
            flat = layer * n_heads + head
            cells.append(
                {
                    "l": layer,
                    "h": head,
                    "dla": round(float(dla_flat[flat]), 4),
                    "patch": round(float(patch[layer, head]), 4),
                    "rank": rank[flat],
                    **({"role": ROLES[(layer, head)]} if (layer, head) in ROLES else {}),
                }
            )

    payload = {
        "layers": list(range(LAYER_START, n_layers)),
        "heads": list(range(n_heads)),
        "nHeadsTotal": int(dla_flat.size),
        "nPrompts": int(d["n_prompts"]),
        # Each lens is normalised to its OWN largest magnitude: the two carry
        # different units (logits vs normalised recovery), so a shared scale
        # would be a lie. The caption says so out loud.
        "lenses": {
            "dla": {
                "label": "Direct logit attribution",
                "unit": "logit difference",
                "max": round(float(np.abs([c["dla"] for c in cells]).max()), 4),
            },
            "patch": {
                "label": "Activation patching",
                "unit": "normalized recovery at END",
                "max": round(float(np.abs([c["patch"] for c in cells]).max()), 4),
            },
        },
        "cells": cells,
    }

    out = HERE / "_lens-data.html"
    out.write_text(
        "<!-- GENERATED by make_lens_data.py from _data.npz — do not edit. -->\n"
        '<script type="application/json" id="ioi-lens-data">\n'
        + json.dumps(payload, separators=(",", ":"))
        + "\n</script>\n",
        encoding="utf-8",
    )
    print(f"wrote {out} ({out.stat().st_size} bytes, {len(cells)} heads)")


if __name__ == "__main__":
    main()
