#!/usr/bin/env python3
"""The résumé adapter: one source, two renderers.

    tools/resume/resume.toml            the content, and nothing else
        ├── resume/_body.md             the page's body (site language; committed)
        └── build/Resume.tex ──latexmk──► assets/Ameya_Panchal_Resume.pdf

Default run (no flags) regenerates resume/_body.md only. It is wired as the
project's Quarto pre-render hook, so the page can never drift from the source.

    python3 tools/resume/build.py --pdf

additionally fills template.tex's content region, runs latexmk, and copies the
PDF into assets/. Run it whenever the content changes; the PDF is a build
artifact, never edited by hand.

Same split as the figures' compute.py/plot.py: content computed once,
presentation per surface. The PDF is the SUBSET renderer (contact items with
web = false — the phone number — never reach the public page); the page is
the superset (entry headings become real links via web_url/url).

Zero dependencies beyond Python 3.11+ (tomllib) and, for --pdf, the TeX
toolchain the template already requires (latexmk + carlito).
"""

import argparse
import html
import re
import shutil
import subprocess
import sys
import tomllib
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
BODY_MD = ROOT / "resume" / "_body.md"
PDF_OUT = ROOT / "assets" / "Ameya_Panchal_Resume.pdf"


# ---- text conversions -------------------------------------------------------

def tex_text(s: str) -> str:
    """Plain content string -> the template's TeX conventions."""
    for a, b in (("&", r"\&"), ("%", r"\%"), ("#", r"\#"), ("$", r"\$")):
        s = s.replace(a, b)
    # χ², with or without a trailing " = <number>", becomes one math span so
    # the equals sign keeps math spacing (matches the hand-written original).
    s = re.sub(r"χ²( = [\d.]+)?", lambda m: r"$\chi^2" + (m.group(1) or "") + "$", s)
    s = s.replace(" · ", r"\sep ")
    s = s.replace("—", "---").replace("–", "--")
    # Interword (not sentence-ending) spaces after abbreviations the résumé uses.
    s = s.replace("Prof. ", "Prof.\\ ").replace(" al. ", " al.\\ ")
    s = re.sub(r"\*(.+?)\*", r"\\emph{\1}", s)
    return s


def web_text(s: str) -> str:
    """Plain content string -> page HTML (unicode kept as itself)."""
    s = html.escape(s)
    s = re.sub(r"\*(.+?)\*", r"<em>\1</em>", s)
    return s


# ---- the PDF (subset renderer) ----------------------------------------------

def gen_tex(data: dict) -> str:
    out = []

    out.append("%----------HEADING----------")
    out.append("\\begin{center}")
    out.append("  {\\sizeName\\bfseries " + tex_text(data["name"]) + "}\\\\[\\gapS]")
    out.append("  \\rule{\\linewidth}{0.6pt}\\\\[\\gapS]")
    items = []
    for c in data["contact"]:
        t = tex_text(c["text"])
        boxed = f"\\mbox{{\\href{{{c['href']}}}{{{t}}}}}" if "href" in c else f"\\mbox{{{t}}}"
        items.append(boxed)
    out.append("  {\\sizeContact\n    " + "\\sep\n    ".join(items) + "%\n  }")
    out.append("\\end{center}")

    for sec in data["sections"]:
        out.append("\n\n%----------" + sec["title"].upper() + "----------")
        out.append("\\section{" + tex_text(sec["title"]) + "}")

        for e in sec.get("entries", []):
            out.append("")
            out.append("\\entry")
            out.append(f"  {{{tex_text(e['heading'])}}}{{{tex_text(e.get('location', ''))}}}")
            out.append(f"  {{{tex_text(e['detail'])}}}{{{tex_text(e['dates'])}}}")
            if "url" in e:
                out.append(f"\\entryurl{{{e['url']}}}")
            out.append("\\begin{points}")
            for b in e.get("bullets", []):
                out.append("  \\item " + tex_text(b))
            out.append("\\end{points}")

        if sec.get("skills"):
            out.append("")
            out.append("\\vspace{\\gapS}")
            for sk in sec["skills"]:
                out.append(f"\\skillrow{{{tex_text(sk['label'])}}}{{{tex_text(sk['text'])}}}")

    template = (HERE / "template.tex").read_text()
    assert "@@CONTENT@@" in template, "template.tex lost its content marker"
    return template.replace("@@CONTENT@@", "\n".join(out))


# ---- the page body (superset renderer) --------------------------------------

def gen_web(data: dict) -> str:
    out = [
        "<!-- GENERATED by tools/resume/build.py from resume.toml — do not edit."
        " Regenerates on every quarto render (pre-render hook). -->",
        "",
        "```{=html}",
        f'<p class="cv-filing">Updated {web_text(data["updated"])}'
        ' · <a href="../assets/Ameya_Panchal_Resume.pdf">Download the PDF</a></p>',
        "```",
    ]

    for sec in data["sections"]:
        out.append("")
        out.append("## " + sec["title"])
        out.append("")
        out.append("```{=html}")

        for e in sec.get("entries", []):
            link = e.get("web_url") or e.get("url")
            head = web_text(e["heading"])
            if link:
                head = f'<a href="{link}">{head}</a>'
            out.append('<article class="cv-entry">')
            out.append('  <div class="cv-row">')
            out.append(f'    <p class="cv-head">{head}</p>')
            out.append(f'    <p class="cv-when">{web_text(e["dates"])}</p>')
            out.append("  </div>")
            out.append('  <div class="cv-row">')
            out.append(f'    <p class="cv-detail">{web_text(e["detail"])}</p>')
            if e.get("location"):
                out.append(f'    <p class="cv-where">{web_text(e["location"])}</p>')
            out.append("  </div>")
            if e.get("bullets"):
                out.append('  <ul class="cv-points">')
                for b in e["bullets"]:
                    out.append(f"    <li>{web_text(b)}</li>")
                out.append("  </ul>")
            out.append("</article>")

        for sk in sec.get("skills", []):
            out.append(
                f'<p class="cv-skill"><strong>{web_text(sk["label"])}:</strong> '
                f'{web_text(sk["text"])}</p>'
            )

        out.append("```")

    return "\n".join(out) + "\n"


# ---- drivers ----------------------------------------------------------------

def build_pdf(data: dict) -> None:
    build_dir = HERE / "build"
    build_dir.mkdir(exist_ok=True)
    (build_dir / "Resume.tex").write_text(gen_tex(data))
    proc = subprocess.run(
        ["latexmk", "-pdf", "-interaction=nonstopmode", "Resume.tex"],
        cwd=build_dir, capture_output=True, text=True,
    )
    if proc.returncode != 0:
        sys.stderr.write(proc.stdout[-3000:] + "\n" + proc.stderr[-1000:] + "\n")
        sys.exit("latexmk failed — see log above")
    shutil.copy(build_dir / "Resume.pdf", PDF_OUT)
    print(f"PDF: {PDF_OUT.relative_to(ROOT)}")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--pdf", action="store_true",
                    help="also build the PDF via latexmk and copy it into assets/")
    args = ap.parse_args()

    data = tomllib.loads((HERE / "resume.toml").read_text())

    BODY_MD.parent.mkdir(exist_ok=True)
    body = gen_web(data)
    if not BODY_MD.exists() or BODY_MD.read_text() != body:
        BODY_MD.write_text(body)
        print(f"page body: {BODY_MD.relative_to(ROOT)} (updated)")

    if args.pdf:
        build_pdf(data)


if __name__ == "__main__":
    main()
