#!/usr/bin/env python3
"""The site adapter: the inventory's view of the home page and the about page.

    tools/resume/resume.toml            the inventory: every fact, said once
        ├── _home.md                    the home page's <section class="road">
        │                               (included by index.qmd; committed)
        ├── about/_body.md              the about page's paragraph, which is
        │                               [person] about, passed through as the
        │                               Markdown it is (committed)
        └── colophon/_panda.md          the Panda section of the colophon, from
                                        tools/home/animations.toml: every move
                                        the panda has, grouped, with its status
                                        (committed)

The same split as tools/resume/build.py, one surface over: this script reads
only the `[person]` block and the items' `home` tables, and writes markup in
the vocabulary assets/home/home.css already styles. It draws nothing itself.

WHAT THE INVENTORY DECIDES
    which items are eras        [items.home] show = "era"
    their order                 newest first, by `when` (else `start`)
    the stamp beside each       that same month
    the rows under an era       its child items (parent = the era's id) with
                                show = "row", then the era's own outputs with
                                home = "row"; "more" goes under the More toggle
    rows keep the inventory's order

WHAT A POST DECIDES FOR ITSELF
    A row links to its item's post or note, and takes its thumbnail from that
    post's own `image:` front matter (the .webp beside it when there is one).
    No image, no picture: the row gets the blank plate.

Runs as a Quarto pre-render hook, after the résumé's. Stdlib only.

_home.md and about/_body.md ARE COMMITTED, like resume/_body.md, and have to be. Quarto resolves
`include` shortcodes while it scans the project, which is BEFORE pre-render
hooks run: with the file missing, the render fails at once ("Include directive
failed"). With a stale copy present, the hook refreshes it and the page renders
from the fresh one (both checked, 2026-09-21). A single-file
`quarto render index.qmd` runs no hooks at all, so run this script by hand
after editing the inventory if you are not doing a full render or a preview.
"""

import re
import sys
import tomllib
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
INVENTORY = ROOT / "tools" / "resume" / "resume.toml"
MOVES = HERE / "animations.toml"
PANDA_OUT = ROOT / "colophon" / "_panda.md"
OUT = ROOT / "_home.md"
ABOUT_OUT = ROOT / "about" / "_body.md"
GENERATED = (
    "<!-- GENERATED by tools/home/build.py from tools/resume/resume.toml — do not"
    " edit. Regenerates on every quarto render (pre-render hook). -->"
)

sys.path.insert(0, str(ROOT / "tools" / "resume"))
from build import MONTHS, web_text  # noqa: E402  (one set of text conventions)

WRITEUP_KINDS = ("post", "note")


# ---- reading a post ---------------------------------------------------------

def front_matter_image(folder: str) -> str | None:
    """A post's `image:` from its own front matter, or None."""
    text = (ROOT / folder / "index.qmd").read_text()
    block = text.split("---", 2)[1] if text.startswith("---") else ""
    found = re.search(r"^image:\s*(.+?)\s*$", block, flags=re.M)
    return found.group(1).strip("\"'") if found else None


def thumbnail(folder: str) -> str | None:
    """Site-relative path of a post's thumbnail, preferring the shipped .webp."""
    image = front_matter_image(folder)
    if image is None:
        return None
    webp = Path(folder) / Path(image).with_suffix(".webp")
    return str(webp) if (ROOT / webp).exists() else str(Path(folder) / image)


# ---- selecting --------------------------------------------------------------

def writeup(item: dict) -> dict | None:
    """The item's first post or note: what its row links to."""
    return next((o for o in item.get("outputs", []) if o["kind"] in WRITEUP_KINDS), None)


def rows_of(era: dict, items: list, show: str) -> list:
    """The rows filed under an era at one level ("row" or "more").

    Child items first, then the era's own outputs, each in inventory order.
    A row is a plain dict: title, line, and the folder it links to.
    """
    children = [
        {"title": i["home"]["title"], "line": i["home"]["line"], "folder": writeup(i)["path"]}
        for i in items
        if i.get("parent") == era["id"] and i.get("home", {}).get("show") == show and writeup(i)
    ]
    own = [
        {"title": o["home_title"], "line": o["home_line"], "folder": o["path"]}
        for o in era.get("outputs", [])
        if o.get("home") == show
    ]
    return children + own


def eras_of(items: list) -> list:
    """The items that are nodes on the road, newest first."""
    eras = [i for i in items if i.get("home", {}).get("show") == "era"]
    return sorted(eras, key=lambda i: i["home"].get("when", i["start"]), reverse=True)


# ---- writing ----------------------------------------------------------------

def row_html(row: dict, indent: str) -> str:
    thumb = thumbnail(row["folder"])
    picture = (
        f'<img class="road-thumb" src="{thumb}" alt="" loading="lazy">'
        if thumb
        else '<span class="road-thumb is-blank"></span>'
    )
    return (
        f'{indent}<li><a href="{row["folder"]}/">{picture}'
        f'<strong>{web_text(row["title"])}</strong><em>{web_text(row["line"])}</em></a></li>'
    )


def work_html(rows: list, indent: str) -> list:
    if not rows:
        return []
    return [f'{indent}<ul class="road-work">', *(row_html(r, indent + "  ") for r in rows), f"{indent}</ul>"]


def era_html(era: dict, items: list) -> list:
    view = era["home"]
    year, month = view.get("when", era["start"]).split("-")
    tag = f'<span class="road-tag">{web_text(view["tag"])}</span>' if "tag" in view else ""
    more = work_html(rows_of(era, items, "more"), "            ")
    return [
        '      <div class="road-era">',
        f'        <p class="road-when"><small>{MONTHS[int(month) - 1].upper()}</small>{year}</p>',
        f'        <p class="road-name" role="heading" aria-level="2">{web_text(view["name"])}{tag}</p>',
        f'        <p class="road-role">{web_text(view["role"])}</p>',
        f'        <p class="road-what">{web_text(view["what"])}</p>',
        *work_html(rows_of(era, items, "row"), "        "),
        *(['        <details class="road-more">', "          <summary>More</summary>",
           *more, "        </details>"] if more else []),
        "      </div>",
    ]


def section_html(inventory: dict) -> str:
    person = inventory["person"]
    items = inventory["items"]
    headline = "".join(f"<span>{web_text(line)}</span>" for line in person["headline"])
    eras = [line for era in eras_of(items) for line in (*era_html(era, items), "")]
    links = [f'    <a href="{l["href"]}">{web_text(l["label"])}</a>' for l in person["links"]]
    return "\n".join([
        '<section class="road" id="top">',
        "",
        '  <div class="road-hero">',
        '    <div class="road-stage" aria-hidden="true"><img src="assets/favicon.svg" alt=""></div>',
        f'    <p id="hero-headline" class="road-ident" role="heading" aria-level="1">{web_text(person["name"])}</p>',
        f'    <p class="road-title">{headline}</p>',
        f'    <p class="road-now">{web_text(person["now"])}</p>',
        "  </div>",
        "",
        '  <div class="road-track">',
        '    <div class="road-eras">',
        '      <div class="road-spine" aria-hidden="true"></div>',
        '      <p class="road-label" aria-hidden="true">The road</p>',
        "",
        *eras[:-1],
        "    </div>",
        "",
        '    <div class="road-end">',
        "      <p>End of the road, for now.</p>",
        "      <p>Thanks for walking it with me.</p>",
        "    </div>",
        "  </div>",
        "",
        '  <nav class="road-foot" aria-label="Profile links">',
        '    <a href="#top">Back to start</a>',
        *links,
        "  </nav>",
        "</section>",
    ])


# ---- the colophon's Panda section -------------------------------------------

GROUPS = [
    ("cel", "Cels", "What the sprite sheet can draw: every pose and cycle, and the hat."),
    ("primitive", "Primitives", "Motions the code composes from cels."),
    ("walker", "The hat panda", "The observer's own behaviours."),
    ("troupe", "A roamer", "One panda at a time going strange: the tier-one anomalies."),
    ("ensemble", "Ensembles", "Several pandas acting together."),
    ("scene", "Scenes", "Entrances, tableaux, whole-page choreography."),
]
STATUS_WORD = {
    "live": "on the home page",
    "shipped": "built, not on the page",
    "retired": "retired",
    "reverted": "reverted",
    "rejected": "rejected unbuilt",
}


def panda_md(moves: list) -> str:
    out = []
    for key, title, lead in GROUPS:
        rows = [m for m in moves if m["group"] == key]
        if not rows:
            continue
        out += [f"### {title}", "", lead, "", "::: {.colo-spec}"]
        for m in rows:
            dd = web_text(m["how"])
            if m.get("note"):
                dd += f" *{web_text(m['note'])}*"
            status = STATUS_WORD[m["status"]]
            out += [
                f'{web_text(m["name"])}',
                f":   {dd}",
                f'    <span class="colo-status is-{m["status"]}">{status}</span>',
                "",
            ]
        out += [":::", ""]
    return "\n".join(out)


def write_if_changed(path: Path, body: str, label: str) -> None:
    if not path.exists() or path.read_text() != body:
        path.write_text(body)
        print(f"{label}: {path.relative_to(ROOT)} (updated)")


def main() -> None:
    inventory = tomllib.loads(INVENTORY.read_text())
    home = "\n".join([GENERATED, "", "```{=html}", section_html(inventory), "```", ""])
    about = "\n".join([GENERATED, "", inventory["person"]["about"].strip(), ""])
    write_if_changed(OUT, home, "home page")
    write_if_changed(ABOUT_OUT, about, "about page")
    moves = tomllib.loads(MOVES.read_text())["moves"]
    panda_header = GENERATED.replace("tools/resume/resume.toml", "tools/home/animations.toml")
    write_if_changed(PANDA_OUT, "\n".join([panda_header, "", panda_md(moves)]), "colophon panda")


if __name__ == "__main__":
    main()
