#!/usr/bin/env python3
"""Bake the hero plate's attention weights: assets/site/hero-plate-data.html.

The homepage plate ("a head reads this page") draws real attention from the
induction post's model — Niche, the 6-block character-level transformer — over
the site's own headline. No model runs in the browser: this script runs it once,
here, and freezes the two heads the plate shows into a JSON block that
_quarto.yml inlines after the body on every page. Re-run when the headline
changes (the string below MUST match index.qmd's .hero-headline text, character
for character — the plate renders THIS string, so a drift would be visible).

    ~/mech_interp/Niche/venv/bin/python tools/hero-plate/compute.py

Which heads, and why these two:
  * B5H0 — the copying head the induction post is about. On this string its
    clearest move is at the second "-ented," where it looks back at the end of
    the first; the long arcs to the first letter are the attention sink.
  * B0H1 — the model's cleanest previous-token head (mean 0.95 on the diagonal
    below the main one, measured over this string). Shown so the induction
    pattern has something ordinary to be read against.

Sparse on purpose: per query position, the top-4 targets at weight >= 0.05,
rounded to two places. ~3 KB, paid on every page as inline JSON.
"""

import json
import os
import sys
from pathlib import Path

import torch

ROOT = Path(__file__).resolve().parents[2]
NICHE = Path(os.environ.get("NICHE_REPO", Path.home() / "mech_interp" / "Niche"))
sys.path.insert(0, str(NICHE / "interp"))
from niche_classes import load_model  # noqa: E402

HEADLINE = "LLM circuitry — implemented, documented, shown off."
HEADS = {"induction": (5, 0), "prev": (0, 1)}
TOP_K = 4
MIN_W = 0.05

m = load_model(str(NICHE / "niche_model.pt"), map_location="cpu")
m.model.eval()
missing = [c for c in HEADLINE if c not in m.stoi]
if missing:
    sys.exit(f"hero-plate: characters not in Niche's vocab: {missing!r}")

idx = torch.tensor([[m.stoi[c] for c in HEADLINE]])
with torch.no_grad():
    m.model(idx, store_attn=True)

out = {"text": HEADLINE, "heads": {}}
for name, (b, h) in HEADS.items():
    A = m.model.blocks[b].comp_full_attend.attn_weights[0, h]
    rows = []
    for i in range(len(HEADLINE)):
        w, j = torch.topk(A[i], min(TOP_K, i + 1))
        rows.append([[int(jj), round(float(ww), 2)] for ww, jj in zip(w, j) if ww >= MIN_W])
    out["heads"][name] = {"label": f"B{b}H{h}", "rows": rows}

target = ROOT / "assets" / "site" / "hero-plate-data.html"
target.write_text(
    "<!-- Generated by tools/hero-plate/compute.py — do not edit. Real attention\n"
    "     of the induction post's model over the homepage headline; consumed by\n"
    "     assets/site/hero-plate.html. -->\n"
    '<script type="application/json" id="hero-plate-data">'
    + json.dumps(out, ensure_ascii=False, separators=(",", ":"))
    + "</script>\n"
)
print(f"hero-plate: wrote {target.relative_to(ROOT)} ({target.stat().st_size // 1024 + 1} KB)")
